---
# vim:ft=ansible:

# We do this via the logged in user, so that ssh forwarding agent can be utilized.
# No ssh keys repuired in production.

- name: clone app to tmp
  sudo: no
  git: repo={{ repo }}
       dest=/tmp/{{ domain }}
       accept_hostkey=yes
       depth=1
       version={{ git_version }}

# We move to our build user, utilize sudo so we KNOW we have perms.
- name: move to build directory
  sudo: yes
  command: > 
           rsync --recursive --links --delete-after --whole-file --cvs-exclude
           /tmp/{{ domain }}/
           {{ build_path }}/{{ domain }}/application

# Remove dir created by clone.
- name: remove tmp directory from git clone
  file: >
       path=/tmp/{{ domain }}
       state=absent

- name: change ownership of application to build_user
  sudo: yes
  file: path={{ build_path }}/{{ domain }}
        mode=0755
        owner='{{ build_user }}'
        group='{{ build_user }}'
        state=directory
  tags:
    - debug

# TOOD handle web user group for RPM vs Debian systems.
- name: change web_root dir permissions
  file: path={{ web_root }}/{{ domain }}
        mode=0755
        owner='{{ build_user }}'
        group='www-data'
        state=directory

- name: install virtualenv requirements
  sudo_user: '{{ item.appuser }}'
  pip: requirements={{ build_path }}/{{ domain }}/application/requirements.txt
       virtualenv={{ build_path }}/{{ domain }}

# We're gonna use a user with a home dir, because we don't want a libs living in
# www directory unless we have to.
- name: generate HTML 
  command: >
          {{ build_path }}/{{ domain }}/bin/python
          {{ build_path }}/{{ domain }}/bin/pelican
          -s publishconf.py
          -o {{ web_root }}/{{ domain }}
          chdir={{ build_path }}/{{ domain }}/application

# TOOD handle web user group for RPM vs Debian systems.
- name: make sure webserver group has read permissions
  file: path={{ web_root }}/{{ domain }}
        mode=0755
        owner='{{ build_user }}'
        group='www-data'
        state=directory
        recurse=yes
