---
# vim:ft=ansible:

# Install any python system dependencies.
# TOOD handle for RPM systems
- name: install python-dev
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python-pip

- name: install virtualenv package
  pip: name=virtualenv

- name: add deploy_user
  user: name={{ deploy_user }} system=yes append=yes shell=/usr/sbin/nologin

- include: deploy.yml
  tags:
    - deploy
